language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t hdtyler/docker-react -f ./section_06/frontend/Dockerfile.dev ./section_06/frontend/

script:
    - docker run -e CI=true hdtyler/docker-react npm run test