version: '3'
# "service is like a type of container"
services:
    redis-server: # this gets a dns entry, possibly via /etc/hosts?
        image: 'redis'
    node-app:
        build: . # build the image in the current directory
        ports:
            - "4001:8081" # localmachine -> container port
        restart: on-failure